api:
  google:
    requests-key: ""
    maps-key: ""
  ns:
    url: "http://webservices.ns.nl/ns-api-stations-v2"
    username: ""
    password: ""
  twilio:
    username: ""
    password: ""
files:
  mechanics: "mechanics.xml"
  notifications: "notifications.xml"
  database: "nsdefect.db"
tkinter:
  button:
    width: 110
    height: 70
    backgroundHex: "#212b5c"
    foregroundHex: "#ffffff"
    relief: FLAT
  title: "NS Defect Overview"
  window:
    width: 800
    height: 533
  logging: False
